services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle_data:/bundle/vendor:cached
    links:
      - 'db:db'
      - 'redis:redis'
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: >
            bash -c "bundle install &&
            bundle exec rails db:create &&
            bundle exec rails db:migrate &&
            bundle exec rails server -b 0.0.0.0"
  redis:
    image: redis:6-alpine
    command: redis-server
    volumes:
      - 'redis_data:/data'
volumes:
  db_data:
  redis_data:
  bundle_data:

version: '3'
