services:
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres
    ports:
      - 5432:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - .env
    environment:
      - PORT=3004
      - RAILS_ENV=development
    command: >
            bash -c "bundle install &&
            bundle exec rails db:setup && 
            bundle exec rails db:migrate && 
            bundle exec rails server -b 0.0.0.0"
    depends_on:
      - db
    image: paylink
    networks:
      default:
        aliases:
        - paylink
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle_data:/bundle/vendor:cached
    stdin_open: true
    tty: true
volumes:
  bundle_data:

version: '3'
