services:
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:13.6-alpine
    ports:
      - 5432:5432
  web:
    build: .
    command: >
            bash -c "bundle install &&
            bundle exec rails db:create && 
            bundle exec rails db:migrate &&
            bundle exec rails s -b 0.0.0.0"
    depends_on:
      - db
    image: siwapp/siwapp
    networks:
      default:
        aliases:
        - siwapp
    ports:
      - 3001:3000
    environment:
      - RAILS_ENV=production
    volumes:
      - .:/app
    stdin_open: true
    tty: true
version: '3'
